{
	"version": 1531386511,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/imglogo-sheet0.png",
		"images/texhistoria-sheet0.png",
		"images/botão-sheet0.png",
		"images/botãodisparo-sheet0.png",
		"images/btthome-sheet0.png",
		"images/bttpause-sheet0.png",
		"images/bttrestart-sheet0.png",
		"images/bttsound-sheet0.png",
		"images/carrinho-sheet0.png",
		"images/chao-sheet0.png",
		"images/char-sheet0.png",
		"images/char-sheet1.png",
		"images/char-sheet2.png",
		"images/char-sheet3.png",
		"images/control-sheet0.png",
		"images/final-sheet0.png",
		"images/botãoicone-sheet0.png",
		"images/pilhaicone-sheet0.png",
		"images/pilha-sheet0.png",
		"images/imgpiece-sheet0.png",
		"images/jump-sheet0.png",
		"images/plataforma-sheet0.png",
		"images/sensordireção-sheet0.png",
		"images/vortéx-sheet0.png",
		"images/pieceicone-sheet0.png",
		"images/pieceicone-sheet1.png",
		"images/fios-sheet0.png",
		"images/fios-sheet1.png",
		"images/bar-sheet0.png",
		"images/bar-sheet1.png",
		"images/bcreditsx-sheet0.png",
		"images/bhelp-sheet0.png",
		"images/bnewgame-sheet0.png",
		"images/equisbar-sheet0.png",
		"images/sxffundo-sheet0.png",
		"images/nomejogo-sheet0.png",
		"media/plantão da globo (8 bit)- (online-audio-converter.com).ogg",
		"media/juhani junkala [retro game music pack] ending.m4a",
		"media/juhani junkala [retro game music pack] ending.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}