{
	"version": 1533204823,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/imglogo-sheet0.png",
		"images/texhistoria-sheet0.png",
		"images/botão-sheet0.png",
		"images/botãodisparo-sheet0.png",
		"images/btmenu-sheet0.png",
		"images/btpausa-sheet0.png",
		"images/btreiniciar-sheet0.png",
		"images/btsom-sheet0.png",
		"images/btsom-sheet1.png",
		"images/carrinho-sheet0.png",
		"images/chao-sheet0.png",
		"images/char-sheet0.png",
		"images/char-sheet1.png",
		"images/char-sheet2.png",
		"images/controle-sheet0.png",
		"images/final-sheet0.png",
		"images/botãoicone-sheet0.png",
		"images/pilhaicone-sheet0.png",
		"images/pilha-sheet0.png",
		"images/imgpedaço-sheet0.png",
		"images/jump-sheet0.png",
		"images/plataforma-sheet0.png",
		"images/sensordireção-sheet0.png",
		"images/vortéx-sheet0.png",
		"images/vortéx-sheet1.png",
		"images/vortéx-sheet2.png",
		"images/vortéx-sheet3.png",
		"images/iconepedaço-sheet0.png",
		"images/iconepedaço-sheet1.png",
		"images/fios-sheet0.png",
		"images/fios-sheet1.png",
		"images/jumpicone-sheet0.png",
		"images/boneco_entrada-sheet0.png",
		"images/imgcorda-sheet0.png",
		"images/bg-sheet0.png",
		"images/janela-sheet0.png",
		"images/btcreditos-sheet0.png",
		"images/btajuda-sheet0.png",
		"images/btnovojogo-sheet0.png",
		"images/equisjanela-sheet0.png",
		"images/sxffundo-sheet0.png",
		"images/nomejogo-sheet0.png",
		"images/tutorialbotão-sheet0.png",
		"images/sensor3-sheet0.png",
		"media/plantão da globo (8 bit)- (online-audio-converter.com).ogg",
		"media/juhani junkala [retro game music pack] ending.m4a",
		"media/juhani junkala [retro game music pack] ending.ogg",
		"media/button1 (online-audio-converter.com).ogg",
		"media/391658__jeckkech__collision.m4a",
		"media/391658__jeckkech__collision.ogg",
		"media/332056__qubodup__fast-collision.m4a",
		"media/332056__qubodup__fast-collision.ogg",
		"media/naruto-shippuden-opening-6-piano-cover-sign-flow (online-audio-converter.com).ogg",
		"media/350903__cabled-mess__jump-c-03.m4a",
		"media/350903__cabled-mess__jump-c-03.ogg",
		"media/350981__cabled-mess__lose-c-09.m4a",
		"media/350981__cabled-mess__lose-c-09.ogg",
		"media/391539__mativve__electro-win-sound.m4a",
		"media/391539__mativve__electro-win-sound.ogg",
		"media/naruto-shippuden-opening-6-piano-cover-sign-flow- (online-audio-converter.com).ogg",
		"media/131409__ecfike__oh-no-4.m4a",
		"media/131409__ecfike__oh-no-4.ogg",
		"media/344778__rokzroom__dilemma-music-loop.m4a",
		"media/344778__rokzroom__dilemma-music-loop.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}