{
	"version": 1527157260,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/ilogo-sheet0.png",
		"images/ifundo-sheet0.png",
		"images/ienigmas-sheet0.png",
		"images/ienigmas-sheet1.png",
		"images/iportas-sheet0.png",
		"images/iportas-sheet1.png",
		"images/sensorportas-sheet0.png",
		"images/f1tiledbackground.png",
		"images/sensorvilão-sheet0.png",
		"images/ivilão-sheet0.png",
		"images/ipedrawin-sheet0.png",
		"images/sensorquestao-sheet0.png",
		"images/sensorquestao-sheet1.png",
		"images/sxffundo-sheet0.png",
		"images/cristalvida-sheet0.png",
		"images/igameover-sheet0.png",
		"images/iwin-sheet0.png",
		"images/bsound-sheet0.png",
		"images/bsound-sheet1.png",
		"images/itiledbackground.png",
		"images/creditsfont-sheet0.png",
		"images/newgamefont-sheet0.png",
		"images/titlefont-sheet0.png",
		"images/bnext-sheet0.png",
		"images/imonstrostorie-sheet0.png",
		"images/imonstrostorie-sheet1.png",
		"images/bhome-sheet0.png",
		"images/sprite-sheet0.png",
		"media/dream 2 (ambience).m4a",
		"media/dream 2 (ambience).ogg",
		"media/button1 (online-audio-converter.com).ogg",
		"media/evil laugh (online-audio-converter.com).ogg",
		"media/game over sound effect.ogg",
		"media/oh no- sound effect.ogg",
		"media/requiem - tasogare otome x amnesia - piano (online-audio-converter.com)hg (1).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}