{
	"version": 1546604733,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/sayodele-sheet0.png",
		"images/sayodele-sheet1.png",
		"images/sayodele-sheet2.png",
		"images/sayodele-sheet3.png",
		"images/blocoayodele-sheet0.png",
		"images/ifundo-sheet0.png",
		"images/schao-sheet0.png",
		"images/sfundomeni-sheet0.png",
		"images/sfruta-sheet0.png",
		"images/sfruta-sheet1.png",
		"images/sfruta-sheet2.png",
		"images/sinstruções-sheet0.png",
		"media/ayo - ataque.ogg",
		"media/ayo - coleta.ogg",
		"media/ayodele - passos.ogg",
		"media/ayo - pular.ogg",
		"media/oxossi.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}